[package]
name = "rigour"
version = "0.1.0"
edition = "2024"
authors = ["CryptoPatrick <cryptopatrick@gmail.com>"]

###############################################################################
description = "Agent Engineering for Automotive Systems"
documentation = "https://docs.rs/rigour"
homepage = "https://github.com/cryptopatrick/rigour"
repository = "https://github.com/cryptopatrick/rigour"
readme = "README.md"
keywords = ["<KEYWORD1>", "<KEYWORD2>" ]
license = "MIT"
autotests = false

###############################################################################
[lib]
name = "rigour"
path = "src/lib.rs"

[[test]]
name = "tests"
path = "tests/test.rs"

###############################################################################
[dependencies]
